# -- 코드를 입력하세요
# SELECT
# A.CAR_ID,
# CASE
#     WHEN (DATEDIFF(END_DATE , START_DATE) + 1) >= 90
#         THEN (DATEDIFF(END_DATE , START_DATE) + 1) * A.DAILY_FEE
#     ELSE (DATEDIFF(END_DATE , START_DATE) + 1) * A.DAILY_FEE
# END AS FEE,
# (DATEDIFF(END_DATE , START_DATE) + 1) * DAILY_FEE
# FROM
# CAR_RENTAL_COMPANY_CAR A 
#     JOIN
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#     ON A.CAR_ID = B.CAR_ID AND CAR_TYPE = '트럭'
# # GROUP BY CAR_ID



WITH HISTORY AS (
    SELECT H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(END_DATE,START_DATE) + 1 AS DURATION,
        CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭')
SELECT H.HISTORY_ID,
       CASE WHEN H.DURATION_TYPE = '7일 이상' THEN ROUND(H.DAILY_FEE*H.DURATION*(1-P.DISCOUNT_RATE/100),0)
            WHEN H.DURATION_TYPE = '30일 이상' THEN ROUND(H.DAILY_FEE* H.DURATION*(1-P.DISCOUNT_RATE/100),0)
            WHEN H.DURATION_TYPE = '90일 이상' THEN ROUND(H.DAILY_FEE*H.DURATION*(1-P.DISCOUNT_RATE/100),0)
       ELSE ROUND(H.DAILY_FEE * H.DURATION,0)
       END AS FEE
    FROM HISTORY H
       LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON H.DURATION_TYPE = P.DURATION_TYPE 
                                                   AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
